version: 0.6.13

indentation: "    "
tab_size: 4
use_tab_characters: false

command_case: "unchanged"
keyword_case: "unchanged"
line_width: 80
split_definitions: false
split_arguments: true
trailing_commas: true

comment: "#"

define_macros: "CM_DEFINE"

section_order:
  - PROJECT
  - PATHS
  - OPTIONS
  - TARGETS
  - INSTALL

set_command_args_order:
  - CACHE
  - PARENT_SCOPE
  - FORCE
  - APPEND

add_library_args_order:
  - NAME
  - TYPE
  - SOURCES

add_executable_args_order:
  - NAME
  - SOURCES

add_test_args_order:
  - NAME
  - COMMAND
  - SOURCES
